# Generated by Django 5.1.6 on 2025-03-04 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('author', models.CharField(max_length=30)),
                ('element', models.CharField(max_length=30)),
                ('planet', models.CharField(max_length=30)),
                ('incense', models.CharField(max_length=30)),
                ('candle', models.CharField(max_length=30)),
                ('direction', models.CharField(max_length=30)),
                ('source', models.TextField(blank=True, null=True)),
                ('sigil_url', models.URLField(blank=True, null=True)),
                ('appearance', models.TextField()),
                ('service', models.CharField(max_length=255)),
                ('note', models.TextField(blank=True, null=True)),
                ('offering', models.TextField()),
            ],
        ),
    ]
