# Generated by Django 5.1.6 on 2025-03-04 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='default_password', max_length=20),
            preserve_default=False,
        ),
    ]
